# -*- coding: utf-8 -*-
"""PHSAM-Vit_H-L-B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apRlp-mQ0-AGdaQlGkArijj58AzD3bSH
"""

!pip install -q git+https://github.com/facebookresearch/segment-anything.git

import os, cv2, time, json, csv, random
import numpy as np
import torch

from segment_anything import sam_model_registry, SamPredictor

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

# dataset folders
ORIG_IMAGE_DIR = "/content/knee_xray_images"
GT_DIR = "/content/JsonMasks"

# Output folder
OUT_ROOT = "/content/phase1_phsam1_results"
os.makedirs(OUT_ROOT, exist_ok=True)


TOP_RATIO = 0.15
BOTTOM_RATIO = 0.15
LEFT_RATIO = 0.10
RIGHT_RATIO = 0.10


SAMPLE_SIZE = 311
SEED = 42
SAVE_MASKS = False

!mkdir -p /content/weights
!wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -P /content/weights
!wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth -P /content/weights
!wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth -P /content/weights

VIT_B_CKPT = "/content/weights/sam_vit_b_01ec64.pth"
VIT_L_CKPT = "/content/weights/sam_vit_l_0b3195.pth"
VIT_H_CKPT = "/content/weights/sam_vit_h_4b8939.pth"

print("H exists?", os.path.exists(VIT_H_CKPT))
print("L exists?", os.path.exists(VIT_L_CKPT))
print("B exists?", os.path.exists(VIT_B_CKPT))

!pip install ripser

import os, glob, json, time
import numpy as np
import cv2

INPUT_DIR      = "/content/knee_xray_images"        # originals
PREVIEW_DIR    = "/content/centroids_ph_previews"   # previews with dots
SAVE_PREVIEWS  = True
CENTROIDS_JSON = "/content/centroids_ph.json"

# crop ratios (your originals)
TOP_RATIO, BOTTOM_RATIO, LEFT_RATIO, RIGHT_RATIO = 0.15, 0.15, 0.10, 0.10

USE_RIPSER = True
try:
    from ripser import ripser
except Exception as _:
    print("[WARN] ripser not found; continuing without PH diagrams.")
    USE_RIPSER = False

os.makedirs(PREVIEW_DIR, exist_ok=True)

def crop_center(image, top_crop_ratio=TOP_RATIO, bottom_crop_ratio=BOTTOM_RATIO,
                left_crop_ratio=LEFT_RATIO, right_crop_ratio=RIGHT_RATIO):
    h, w = image.shape
    top = int(h * top_crop_ratio)
    bottom = int(h * (1 - bottom_crop_ratio))
    left = int(w * left_crop_ratio)
    right = int(w * (1 - right_crop_ratio))
    return image[top:bottom, left:right]

def process_ph(img, flipped=False):
    """
    Your original logic with safe try/except:
      - crop center
      - optional vertical flip
      - blur + Canny
      - (optional) PH on edge points via ripser
      - largest contour -> centroid via moments
    Returns (cropped_gray, (cx,cy)) or (None, None) on error.
    """
    try:
        image = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
        if image is None:
            raise ValueError("Unreadable image")
        image = crop_center(image)
        if flipped:
            image = cv2.flip(image, 0)

        blur = cv2.GaussianBlur(image, (5, 5), 0)
        edges = cv2.Canny(blur, 50, 150)

        # Optional PH step
        if USE_RIPSER:
            X = np.column_stack(np.where(edges > 0)).T
            if X.size == 0:
                raise ValueError("No edge points found for PH computation.")
            _ = ripser(X, maxdim=2)['dgms']  # not plotting, just keeping PH active

        contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not contours:
            raise ValueError("No contours found.")
        largest_contour = max(contours, key=cv2.contourArea)

        M = cv2.moments(largest_contour)
        if M["m00"] == 0:
            raise ValueError("Invalid contour moment (m00 = 0).")

        centroid_x = int(M["m10"] / M["m00"])
        centroid_y = int(M["m01"] / M["m00"])
        return image, (centroid_x, centroid_y)

    except Exception as e:
        print(f"[SKIP] Error processing {os.path.basename(img)} (flipped={flipped}): {e}")
        return None, None

def run_ph_folder(folder_path):
    centroids = {}
    image_files = sorted(glob.glob(os.path.join(folder_path, "*.png")))  # adjust ext if needed
    if not image_files:
        print(f"[INFO] No .png files in {folder_path}")

    done, skipped = 0, 0
    for img_path in image_files:
        try:
            # original + flipped
            image, c1 = process_ph(img_path, flipped=False)
            flipped_image, c2 = process_ph(img_path, flipped=True)

            if image is None or c1 is None or flipped_image is None or c2 is None:
                skipped += 1
                continue

            filename = os.path.basename(img_path)
            centroids[filename] = [list(c1), list(c2)]

            if SAVE_PREVIEWS:
                vis = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
                cv2.circle(vis, tuple(c1), 5, (0, 255, 0), -1)  # green = original
                cv2.circle(vis, tuple(c2), 5, (255, 0, 0), -1)  # blue  = flipped-in-crop coords
                cv2.imwrite(os.path.join(PREVIEW_DIR, f"PHoutput_{filename}"), vis)

            done += 1
        except Exception as e:
            print(f"[SKIP] Unexpected error {os.path.basename(img_path)}: {e}")
            skipped += 1

    print(f"[PH] done={done}, skipped={skipped}, total={len(image_files)}")
    return centroids, done, skipped, len(image_files)

# -------------------------
# RUN PH ONLY + TIMING
# -------------------------
t0 = time.perf_counter()

centroids, done, skipped, total_files = run_ph_folder(INPUT_DIR)

t1 = time.perf_counter()
total_sec = t1 - t0

# avg time per image (two ways):
# 1) per successfully processed file (more meaningful)
avg_per_done = total_sec / done if done > 0 else float("nan")
# 2) per attempted file (including skipped)
avg_per_total = total_sec / total_files if total_files > 0 else float("nan")

print(f"[TIME] total={total_sec:.3f}s | avg_per_done={avg_per_done:.3f}s/image | avg_per_total={avg_per_total:.3f}s/image")

# Save to JSON so you can load it later in a separate SAM2 step
with open(CENTROIDS_JSON, "w") as f:
    json.dump(centroids, f)
print(f"[SAVE] Centroids JSON -> {CENTROIDS_JSON}")

# Quick peek
print("Sample centroids:", dict(list(centroids.items())[:3]))

import json
with open("/content/centroids_ph.json","r") as f:
    centroids = json.load(f)
print("Number of images:", len(centroids))

PHSAM1_MODELS = {
    "vit_h": {"ckpt": "/content/weights/sam_vit_h_4b8939.pth", "mask_idx": 0},
    "vit_l": {"ckpt": "/content/weights/sam_vit_l_0b3195.pth", "mask_idx": 1},
    "vit_b": {"ckpt": "/content/weights/sam_vit_b_01ec64.pth", "mask_idx": 2},
}

import os
import cv2
import torch
import numpy as np
import time
import json
import csv
import random
from segment_anything import sam_model_registry, SamPredictor

# DEVICE
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# DATA PATHS
ORIG_IMAGE_DIR = "/content/knee_xray_images"
GT_DIR         = "/content/JsonMasks"

# OUTPUT ROOT
OUT_ROOT = "/content/phase1_phsam1_results"
os.makedirs(OUT_ROOT, exist_ok=True)

#crop params
TOP_RATIO = 0.15
BOTTOM_RATIO = 0.15
LEFT_RATIO = 0.10
RIGHT_RATIO = 0.10

def map_centroids_to_original(img_gray, c1, c2):
    h, w = img_gray.shape[:2]
    top = int(h * TOP_RATIO)
    bottom = int(h * (1 - BOTTOM_RATIO))
    left = int(w * LEFT_RATIO)
    right = int(w * (1 - RIGHT_RATIO))
    crop_h = bottom - top

    # c1: add offsets
    x1o = left + int(c1[0])
    y1o = top  + int(c1[1])

    # c2: unflip vertically within the crop, then add offsets
    y2_unflipped = (crop_h - 1) - int(c2[1])
    x2o = left + int(c2[0])
    y2o = top  + y2_unflipped

    # clamp
    x1o = np.clip(x1o, 0, w-1); y1o = np.clip(y1o, 0, h-1)
    x2o = np.clip(x2o, 0, w-1); y2o = np.clip(y2o, 0, h-1)
    return (int(x1o), int(y1o)), (int(x2o), int(y2o))

def dice_score_bin(pred_mask_bin, gt_mask_bin):
    a = pred_mask_bin.astype(bool)
    b = gt_mask_bin.astype(bool)
    inter = np.logical_and(a, b).sum()
    denom = a.sum() + b.sum()
    return 1.0 if denom == 0 else (2.0 * inter / (denom + 1e-8))

def find_gt_path(base_id, original_filename):
    exts = [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]

    # 1) exact same filename first
    candidate = os.path.join(GT_DIR, original_filename)
    if os.path.exists(candidate):
        return candidate

    # 2) base + _mask.<ext>
    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}_mask{e}")
        if os.path.exists(candidate):
            return candidate

    # 3) base + any ext
    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}{e}")
        if os.path.exists(candidate):
            return candidate

    return None

def segment_with_sam_on_original(predictor: SamPredictor, image_path, c1_orig, c2_orig, mask_index=0):
    """
    Runs SAM on the original image using two mapped centroids.
    Returns:
        mask_bin (H, W) np.uint8 (0/1)
        mask_img (H, W) np.uint8 (0/255)
    """
    bgr = cv2.imread(image_path, cv2.IMREAD_COLOR)
    if bgr is None:
        raise ValueError(f"Unreadable image: {image_path}")

    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    predictor.set_image(rgb)

    pts = np.array([c1_orig, c2_orig], dtype=np.float32)
    labels = np.array([1, 1], dtype=np.int32)

    masks, scores, logits = predictor.predict(
        point_coords=pts,
        point_labels=labels,
        multimask_output=True
    )
    masks = np.asarray(masks)

    if masks.shape[0] == 0:
        raise RuntimeError("SAM returned zero masks.")

    if mask_index >= masks.shape[0]:
        raise RuntimeError(f"Requested mask_index={mask_index} but SAM returned only {masks.shape[0]} masks.")

    chosen = masks[mask_index]
    mask_bin = (chosen > 0).astype(np.uint8)
    mask_img = (mask_bin * 255).astype(np.uint8)
    return mask_bin, mask_img

#  model loader
def load_sam_predictor(model_type: str, checkpoint_path: str) -> SamPredictor:
    sam = sam_model_registry[model_type](checkpoint=checkpoint_path).to(device=DEVICE)
    predictor = SamPredictor(sam)
    return predictor

#
def run_phase1_phsam1_single_run(
    centroids_dict: dict,
    model_type: str,
    checkpoint_path: str,
    mask_index: int,
    sample_size: int = 63,
    seed: int = 42,
    save_masks: bool = False
):
    """
    Runs ONE random batch of size=sample_size for one SAM backbone (PHSAM1).
    Computes:
      - avg dice
      - best dice
      - avg time/image
      - total batch time
    Writes per-image CSV and a summary dict.
    """
    random.seed(seed)
    np.random.seed(seed)

    out_dir = os.path.join(OUT_ROOT, f"{model_type}_mask{mask_index}_seed{seed}")
    os.makedirs(out_dir, exist_ok=True)

    predictor = load_sam_predictor(model_type, checkpoint_path)

    #
    eligible = []
    for filename, c_list in centroids_dict.items():
        if not isinstance(c_list, (list, tuple)) or len(c_list) < 2:
            continue
        img_path = os.path.join(ORIG_IMAGE_DIR, filename)
        if not os.path.exists(img_path):
            continue
        base_id = os.path.splitext(filename)[0]
        gt_path = find_gt_path(base_id, filename)
        if gt_path is None or not os.path.exists(gt_path):
            continue
        eligible.append(filename)

    if len(eligible) < sample_size:
        raise ValueError(f"Not enough eligible images with GT. Eligible={len(eligible)}, requested={sample_size}")

    sampled = random.sample(eligible, sample_size)

    rows = []
    dice_list = []
    per_img_times = []

    t_batch0 = time.time()

    for filename in sampled:
        img_path = os.path.join(ORIG_IMAGE_DIR, filename)
        base_id = os.path.splitext(filename)[0]
        gt_path = find_gt_path(base_id, filename)

        # read gray for mapping
        g = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if g is None:
            continue

        c1 = tuple(map(int, centroids_dict[filename][0]))
        c2 = tuple(map(int, centroids_dict[filename][1]))
        c1o, c2o = map_centroids_to_original(g, c1, c2)

        t0 = time.time()
        pred_bin, pred_img = segment_with_sam_on_original(
            predictor, img_path, c1o, c2o, mask_index=mask_index
        )
        t1 = time.time()

        # load + binarize GT
        gt = cv2.imread(gt_path, cv2.IMREAD_UNCHANGED)
        if gt is None:
            continue
        if gt.ndim == 3:
            gt_bin = (np.sum(gt, axis=2) > 0).astype(np.uint8)
        else:
            gt_bin = (gt > 0).astype(np.uint8)

        # resize GT if needed
        if gt_bin.shape != pred_bin.shape:
            gt_bin = cv2.resize(gt_bin, (pred_bin.shape[1], pred_bin.shape[0]), interpolation=cv2.INTER_NEAREST)

        d = dice_score_bin(pred_bin, gt_bin)

        dt = t1 - t0
        dice_list.append(d)
        per_img_times.append(dt)

        pred_name = ""
        if save_masks:
            pred_name = f"{base_id}_pred_{model_type}_mask{mask_index}_dice{d:.4f}.png"
            cv2.imwrite(os.path.join(out_dir, pred_name), pred_img)

        rows.append({
            "filename": filename,
            "id": base_id,
            "gt_path": os.path.basename(gt_path),
            "dice": float(d),
            "time_sec": float(dt),
            "pred_mask_file": pred_name
        })

    t_batch1 = time.time()
    batch_time = t_batch1 - t_batch0

    avg_dice = float(np.mean(dice_list)) if dice_list else 0.0
    best_dice = float(np.max(dice_list)) if dice_list else 0.0
    avg_time_img = float(np.mean(per_img_times)) if per_img_times else 0.0

    # write per-image CSV
    csv_path = os.path.join(out_dir, f"phase1_{model_type}_mask{mask_index}_seed{seed}.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["filename", "id", "gt_file", "dice", "time_sec", "pred_mask_file"])
        for r in rows:
            w.writerow([r["filename"], r["id"], r["gt_path"], f'{r["dice"]:.6f}', f'{r["time_sec"]:.6f}', r["pred_mask_file"]])

        w.writerow([])
        w.writerow(["SUMMARY", "", "", "", "", ""])
        w.writerow(["avg_dice", avg_dice])
        w.writerow(["best_dice", best_dice])
        w.writerow(["avg_time_per_image_sec", avg_time_img])
        w.writerow(["total_batch_time_sec", batch_time])
        w.writerow(["n_images_used", len(rows)])

    summary = {
        "model_type": model_type,
        "checkpoint": checkpoint_path,
        "mask_index": mask_index,
        "seed": seed,
        "sample_size_requested": sample_size,
        "n_images_used": len(rows),
        "avg_dice": avg_dice,
        "best_dice": best_dice,
        "avg_time_per_image_sec": avg_time_img,
        "total_batch_time_sec": float(batch_time),
        "csv_path": csv_path,
        "out_dir": out_dir
    }

    print("✅ PHASE 1 RUN DONE")
    print(summary)
    return summary

# run all PHSAM1 models once
def run_phase1_phsam1_all_models_once(centroids_dict, sample_size=63, seed=42, save_masks=False):
    PHSAM1_MODELS = {
        "vit_h": {"ckpt": "/content/weights/sam_vit_h_4b8939.pth", "mask_idx": 0},
        "vit_l": {"ckpt": "/content/weights/sam_vit_l_0b3195.pth", "mask_idx": 1},
        "vit_b": {"ckpt": "/content/weights/sam_vit_b_01ec64.pth", "mask_idx": 2},
    }

    all_summaries = []
    for model_type, cfg in PHSAM1_MODELS.items():
        s = run_phase1_phsam1_single_run(
            centroids_dict=centroids_dict,
            model_type=model_type,
            checkpoint_path=cfg["ckpt"],
            mask_index=cfg["mask_idx"],
            sample_size=sample_size,
            seed=seed,
            save_masks=save_masks
        )
        all_summaries.append(s)

    # write a combined summary CSV
    summary_csv = os.path.join(OUT_ROOT, f"PHASE1_PHSAM1_SUMMARY_seed{seed}.csv")
    with open(summary_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["model_type", "mask_index", "avg_dice", "best_dice", "avg_time_per_image_sec", "total_batch_time_sec", "n_images_used", "csv_path"])
        for s in all_summaries:
            w.writerow([s["model_type"], s["mask_index"], f'{s["avg_dice"]:.6f}', f'{s["best_dice"]:.6f}', f'{s["avg_time_per_image_sec"]:.6f}', f'{s["total_batch_time_sec"]:.6f}', s["n_images_used"], s["csv_path"]])

    print(f"📌 Combined summary saved to: {summary_csv}")
    return all_summaries, summary_csv

# centroids must already exist from your PH step:

summaries, summary_csv = run_phase1_phsam1_all_models_once(
    centroids_dict=centroids,
    sample_size=63,
    seed=42,
    save_masks=True  # set True if you want predicted masks saved
)

print("centroids exists?", "centroids" in globals())
print("type:", type(centroids) if "centroids" in globals() else None)
print("len(centroids):", len(centroids) if "centroids" in globals() else None)

"""PHSAM1 PHASE 2"""

import os
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

GT_DIR = "/content/JsonMasks"
OUT_ROOT = "/content/phase1_phsam1_results"

# set (save_masks=True) to view masks
MODELS = {
    "ViT-H": "vit_h_mask0_seed42",
    "ViT-L": "vit_l_mask1_seed42",
    "ViT-B": "vit_b_mask2_seed42",
}

def load_bin_mask(path):
    m = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if m is None:
        raise FileNotFoundError(f"Cannot read mask: {path}")
    return (m > 0).astype(np.uint8)

def per_image_prf(pred, gt):
    pred = pred.astype(bool)
    gt   = gt.astype(bool)

    tp = np.logical_and(pred, gt).sum()
    fp = np.logical_and(pred, np.logical_not(gt)).sum()
    fn = np.logical_and(np.logical_not(pred), gt).sum()

    precision = tp / (tp + fp + 1e-8)
    recall    = tp / (tp + fn + 1e-8)
    f1        = (2 * precision * recall) / (precision + recall + 1e-8)
    return float(precision), float(recall), float(f1), int(tp), int(fp), int(fn)

phase2_results = {}          # summary per model
per_image_metrics = {}       # dataframe per model (for boxplots)

for model_name, folder in MODELS.items():
    folder_path = os.path.join(OUT_ROOT, folder)
    csv_path = os.path.join(folder_path, f"phase1_{folder}.csv")

    df = pd.read_csv(csv_path)
    df["dice"] = pd.to_numeric(df["dice"], errors="coerce")
    df = df[df["dice"].notnull()]  # keeps only 63 image rows

    # Accumulate pixel-level confusion across all 63 images
    TP = FP = FN = TN = 0

    rows = []
    for _, r in df.iterrows():
        gt_path = os.path.join(GT_DIR, r["gt_file"])
        pred_path = os.path.join(folder_path, r["pred_mask_file"])

        if (not os.path.exists(gt_path)) or (not os.path.exists(pred_path)):
            continue

        gt = load_bin_mask(gt_path)
        pred = load_bin_mask(pred_path)

        # resize GT to pred if needed
        if gt.shape != pred.shape:
            gt = cv2.resize(gt, (pred.shape[1], pred.shape[0]), interpolation=cv2.INTER_NEAREST)

        precision, recall, f1, tp, fp, fn = per_image_prf(pred, gt)

        # TN: total pixels - (tp+fp+fn)
        total = gt.size
        tn = total - (tp + fp + fn)

        TP += tp; FP += fp; FN += fn; TN += tn

        rows.append({
            "filename": r["filename"],
            "dice": float(r["dice"]),
            "precision": precision,
            "recall": recall,
            "f1": f1
        })

    mdf = pd.DataFrame(rows)
    per_image_metrics[model_name] = mdf

    # Aggregate metrics from summed confusion
    precision_all = TP / (TP + FP + 1e-8)
    recall_all    = TP / (TP + FN + 1e-8)
    f1_all        = (2 * precision_all * recall_all) / (precision_all + recall_all + 1e-8)

    cm = np.array([[TN, FP],
                   [FN, TP]], dtype=np.int64)

    phase2_results[model_name] = {
        "n_images_used": int(len(mdf)),
        "precision_pixel": float(precision_all),
        "recall_pixel": float(recall_all),
        "f1_pixel": float(f1_all),
        "confusion_matrix": cm
    }

# Print results
for model_name, res in phase2_results.items():
    print(f"\n=== {model_name} (63 images) ===")
    print("Images used:", res["n_images_used"])
    print(f"Pixel Precision: {res['precision_pixel']:.4f}")
    print(f"Pixel Recall:    {res['recall_pixel']:.4f}")
    print(f"Pixel F1:        {res['f1_pixel']:.4f}")
    print("Confusion Matrix [ [TN FP], [FN TP] ]:")
    print(res["confusion_matrix"])

import matplotlib.pyplot as plt

# Make sure we have per_image_metrics from Cell 1
labels = list(per_image_metrics.keys())

dice_data = [per_image_metrics[m]["dice"].values for m in labels]
prec_data = [per_image_metrics[m]["precision"].values for m in labels]
rec_data  = [per_image_metrics[m]["recall"].values for m in labels]
f1_data   = [per_image_metrics[m]["f1"].values for m in labels]

def boxplot_metric(data, title, ylabel):
    plt.figure(figsize=(7,5))
    plt.boxplot(data, labels=labels)
    plt.title(title)
    plt.ylabel(ylabel)
    plt.grid(axis="y", alpha=0.3)
    plt.show()

boxplot_metric(dice_data, "PH-SAM1 Dice Distribution (63 Images)", "Dice")
boxplot_metric(prec_data, "PH-SAM1 Precision Distribution (63 Images)", "Precision")
boxplot_metric(rec_data,  "PH-SAM1 Recall Distribution (63 Images)", "Recall")
boxplot_metric(f1_data,   "PH-SAM1 F1 Distribution (63 Images)", "F1-score")
